"""Export repos to Parquet, CSV, JSON, and Markdown report."""
from __future__ import annotations

import json
from datetime import datetime, timezone
from pathlib import Path
from typing import Any


def _flatten_repo(repo: dict) -> dict:
    """Convert JSONB fields to strings for tabular export."""
    flat = dict(repo)
    for key in ("topics", "assigned_domains", "extracted_deps", "matched_signals", "tags", "projects"):
        val = flat.get(key)
        if val is not None and not isinstance(val, str):
            flat[key] = json.dumps(val)
        elif val is None:
            flat[key] = ""
    # Convert datetimes to ISO strings
    for key in ("last_pushed_at", "classified_at", "fetched_at", "first_seen_at", "last_reviewed_at"):
        val = flat.get(key)
        if isinstance(val, datetime):
            flat[key] = val.isoformat()
    return flat


def to_parquet(repos: list[dict], path: Path) -> None:
    """Export repos list to a Parquet file."""
    import pyarrow as pa
    import pyarrow.parquet as pq

    path = Path(path)
    path.parent.mkdir(parents=True, exist_ok=True)

    flat_repos = [_flatten_repo(r) for r in repos]
    if not flat_repos:
        # Write empty parquet
        table = pa.table({})
        pq.write_table(table, str(path))
        return

    # Build table from dicts
    table = pa.Table.from_pylist(flat_repos)
    pq.write_table(table, str(path))


def to_csv(repos: list[dict], path: Path) -> None:
    """Export repos list to a CSV file."""
    import csv

    path = Path(path)
    path.parent.mkdir(parents=True, exist_ok=True)

    flat_repos = [_flatten_repo(r) for r in repos]
    if not flat_repos:
        path.write_text("")
        return

    fieldnames = list(flat_repos[0].keys())
    with open(path, "w", newline="") as f:
        writer = csv.DictWriter(f, fieldnames=fieldnames, extrasaction="ignore")
        writer.writeheader()
        writer.writerows(flat_repos)


def to_json_summary(repos: list[dict], path: Path) -> None:
    """Export a summary JSON with aggregate stats."""
    path = Path(path)
    path.parent.mkdir(parents=True, exist_ok=True)

    total = len(repos)
    top10 = sorted(repos, key=lambda r: r.get("score", 0) or 0, reverse=True)[:10]

    # Count by domain
    domain_counts: dict[str, int] = {}
    for repo in repos:
        domains = repo.get("assigned_domains", [])
        if isinstance(domains, str):
            try:
                domains = json.loads(domains)
            except Exception:
                domains = []
        for d in domains:
            domain_counts[d] = domain_counts.get(d, 0) + 1

    summary = {
        "generated_at": datetime.now(timezone.utc).isoformat(),
        "total_repos": total,
        "domain_counts": domain_counts,
        "top_repos": [
            {
                "id": r.get("id"),
                "score": r.get("score"),
                "stars": r.get("stars"),
                "primary_domain": r.get("primary_domain"),
            }
            for r in top10
        ],
    }

    path.write_text(json.dumps(summary, indent=2, default=str))


def generate_report(repos: list[dict], stats: dict, output_path: Path) -> None:
    """Generate REPORT.md with domain summaries and top repos."""
    output_path = Path(output_path)
    now = datetime.now(timezone.utc).strftime("%Y-%m-%d")

    lines = [
        f"# repo-hub Report — {now}",
        "",
        "Generated by `repo-hub report`. See [docs/WORKFLOW.md](docs/WORKFLOW.md) for details.",
        "",
        "## Summary",
        "",
    ]

    total = stats.get("total", len(repos))
    domain_count = len(stats.get("by_domain", []))
    top_repo = max(repos, key=lambda r: r.get("score", 0) or 0) if repos else None
    top_score = top_repo.get("score", 0) if top_repo else 0

    lines += [
        f"| Metric | Value |",
        f"|---|---|",
        f"| Total repos tracked | {total} |",
        f"| Domains with coverage | {domain_count} |",
        f"| Top score | {top_score} |",
        f"| Generated at | {now} |",
        "",
    ]

    # Group repos by primary domain
    by_domain: dict[str, list[dict]] = {}
    for repo in repos:
        primary = repo.get("primary_domain") or ""
        if primary:
            by_domain.setdefault(primary, []).append(repo)

    lines.append("## Top Repos by Domain")
    lines.append("")

    for domain_id, domain_repos in sorted(by_domain.items()):
        top = sorted(domain_repos, key=lambda r: r.get("score", 0) or 0, reverse=True)[:10]
        if not top:
            continue

        lines.append(f"### {domain_id}")
        lines.append("")
        lines.append("| Repo | Score | Stars | Description |")
        lines.append("|---|---|---|---|")
        for r in top:
            repo_id = r.get("id", "")
            score = r.get("score", 0)
            stars = r.get("stars", 0)
            desc = (r.get("description") or "")[:80].replace("|", "\\|")
            url = r.get("url", "")
            lines.append(f"| [{repo_id}]({url}) | {score} | {stars} | {desc} |")
        lines.append("")

    # New repos (last 7 days)
    lines.append("## New Repos (Last 7 Days)")
    lines.append("")
    now_dt = datetime.now(timezone.utc)
    new_repos = []
    for repo in repos:
        fetched = repo.get("fetched_at")
        if isinstance(fetched, str):
            try:
                fetched = datetime.fromisoformat(fetched.replace("Z", "+00:00"))
            except ValueError:
                continue
        if isinstance(fetched, datetime):
            if fetched.tzinfo is None:
                fetched = fetched.replace(tzinfo=timezone.utc)
            age_days = (now_dt - fetched).total_seconds() / 86400
            if age_days <= 7:
                new_repos.append(repo)

    if new_repos:
        lines.append("| Repo | Score | Domain |")
        lines.append("|---|---|---|")
        for r in sorted(new_repos, key=lambda r: r.get("score", 0) or 0, reverse=True)[:20]:
            repo_id = r.get("id", "")
            score = r.get("score", 0)
            domain = r.get("primary_domain", "")
            url = r.get("url", "")
            lines.append(f"| [{repo_id}]({url}) | {score} | {domain} |")
    else:
        lines.append("_No new repos this week._")

    lines.append("")

    # Domain stats table
    lines.append("## Domain Statistics")
    lines.append("")
    lines.append("| Domain | Repos | Avg Score | Top Score |")
    lines.append("|---|---|---|---|")
    for row in stats.get("by_domain", []):
        lines.append(
            f"| {row.get('domain', '')} | {row.get('cnt', 0)} "
            f"| {row.get('avg_score', 0)} | {row.get('top_score', 0)} |"
        )
    lines.append("")

    output_path.write_text("\n".join(lines))
